"""
GENERATED BY CLAUDE for reference.
transformer_from_scratch.py

A minimal, from-scratch GPT-style (decoder-only) Transformer language model,
implemented entirely in PyTorch with no pretrained weights and no external
NLP libraries. Uses character-level tokenization for simplicity.

Usage:
    1. Put any plain text file named `input.txt` in the same directory
       (e.g. a book, article collection, or your own writing).
    2. Run: python transformer_from_scratch.py
    3. The script will train the model and print sample generated text
       at the end, plus save weights to transformer_lm.pt

Everything below is intentionally verbose/commented for learning purposes.
"""

import math
import torch
import torch.nn as nn
import torch.nn.functional as F


# ------------------------------------------------------------------
# 1. Configuration
# ------------------------------------------------------------------
class Config:
    block_size = 128       # max context length (how many past tokens the model sees)
    n_embd = 256            # embedding dimension
    n_head = 8               # number of attention heads
    n_layer = 6               # number of transformer blocks stacked
    dropout = 0.1
    batch_size = 32
    learning_rate = 3e-4
    max_iters = 3000
    eval_interval = 300
    eval_iters = 50
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    vocab_size = None       # filled in once we've built the tokenizer


# ------------------------------------------------------------------
# 2. Tokenizer (character-level, built from the corpus itself)
# ------------------------------------------------------------------
def build_tokenizer(text):
    chars = sorted(list(set(text)))
    stoi = {ch: i for i, ch in enumerate(chars)}
    itos = {i: ch for i, ch in enumerate(chars)}
    encode = lambda s: [stoi[c] for c in s]
    decode = lambda ids: ''.join(itos[i] for i in ids)
    return encode, decode, len(chars)


# ------------------------------------------------------------------
# 3. Batching: sample random (input, target) chunks
# ------------------------------------------------------------------
def get_batch(data, block_size, batch_size, device):
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i + block_size] for i in ix])
    y = torch.stack([data[i + 1:i + block_size + 1] for i in ix])  # shifted by 1
    return x.to(device), y.to(device)


# ------------------------------------------------------------------
# 4. Single self-attention head
# ------------------------------------------------------------------
class Head(nn.Module):
    def __init__(self, head_size, n_embd, block_size, dropout):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        # causal mask: position i can only attend to positions <= i
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B, T, C = x.shape
        k = self.key(x)      # (B, T, head_size)
        q = self.query(x)    # (B, T, head_size)
        wei = q @ k.transpose(-2, -1) * (C ** -0.5)          # (B, T, T) scaled attention scores
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))  # block future positions
        wei = F.softmax(wei, dim=-1)
        wei = self.dropout(wei)
        v = self.value(x)
        return wei @ v        # (B, T, head_size)


# ------------------------------------------------------------------
# 5. Multi-head attention: run several heads in parallel, combine
# ------------------------------------------------------------------
class MultiHeadAttention(nn.Module):
    def __init__(self, n_head, head_size, n_embd, block_size, dropout):
        super().__init__()
        self.heads = nn.ModuleList(
            [Head(head_size, n_embd, block_size, dropout) for _ in range(n_head)]
        )
        self.proj = nn.Linear(head_size * n_head, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        return self.dropout(self.proj(out))


# ------------------------------------------------------------------
# 6. Position-wise feed-forward network
# ------------------------------------------------------------------
class FeedForward(nn.Module):
    def __init__(self, n_embd, dropout):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.GELU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)


# ------------------------------------------------------------------
# 7. One transformer block: attention + feed-forward, each with
#    a residual connection and pre-LayerNorm
# ------------------------------------------------------------------
class Block(nn.Module):
    def __init__(self, n_embd, n_head, block_size, dropout):
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size, n_embd, block_size, dropout)
        self.ffwd = FeedForward(n_embd, dropout)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))     # residual + attention
        x = x + self.ffwd(self.ln2(x))   # residual + feed-forward
        return x


# ------------------------------------------------------------------
# 8. Full model: embeddings -> stacked blocks -> output head
# ------------------------------------------------------------------
class TransformerLM(nn.Module):
    def __init__(self, vocab_size, n_embd, block_size, n_head, n_layer, dropout):
        super().__init__()
        self.block_size = block_size
        self.token_embedding = nn.Embedding(vocab_size, n_embd)
        self.position_embedding = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(
            *[Block(n_embd, n_head, block_size, dropout) for _ in range(n_layer)]
        )
        self.ln_f = nn.LayerNorm(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        tok_emb = self.token_embedding(idx)                                  # (B, T, C)
        pos_emb = self.position_embedding(torch.arange(T, device=idx.device))  # (T, C)
        x = tok_emb + pos_emb
        x = self.blocks(x)
        x = self.ln_f(x)
        logits = self.lm_head(x)   # (B, T, vocab_size)

        loss = None
        if targets is not None:
            B, T, C = logits.shape
            loss = F.cross_entropy(logits.view(B * T, C), targets.view(B * T))
        return logits, loss

    @torch.no_grad()
    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -self.block_size:]        # crop context to block_size
            logits, _ = self(idx_cond)
            logits = logits[:, -1, :]                    # only need the last time step
            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)
        return idx


# ------------------------------------------------------------------
# 9. Loss estimation helper (averages over multiple batches)
# ------------------------------------------------------------------
@torch.no_grad()
def estimate_loss(model, train_data, val_data, cfg):
    out = {}
    model.eval()
    for split, data in [('train', train_data), ('val', val_data)]:
        losses = torch.zeros(cfg.eval_iters)
        for k in range(cfg.eval_iters):
            X, Y = get_batch(data, cfg.block_size, cfg.batch_size, cfg.device)
            _, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean().item()
    model.train()
    return out


# ------------------------------------------------------------------
# 10. Training entry point
# ------------------------------------------------------------------
def main():
    cfg = Config()
    torch.manual_seed(1337)

    # --- load your corpus ---
    with open('input.txt', 'r', encoding='utf-8') as f:
        text = f.read()

    encode, decode, vocab_size = build_tokenizer(text)
    cfg.vocab_size = vocab_size
    print(f"vocab size: {vocab_size}, corpus length: {len(text)} characters")

    data = torch.tensor(encode(text), dtype=torch.long)
    n = int(0.9 * len(data))
    train_data, val_data = data[:n], data[n:]

    model = TransformerLM(
        cfg.vocab_size, cfg.n_embd, cfg.block_size, cfg.n_head, cfg.n_layer, cfg.dropout
    ).to(cfg.device)
    print(f"{sum(p.numel() for p in model.parameters()) / 1e6:.2f}M parameters")

    optimizer = torch.optim.AdamW(model.parameters(), lr=cfg.learning_rate)

    for it in range(cfg.max_iters):
        if it % cfg.eval_interval == 0 or it == cfg.max_iters - 1:
            losses = estimate_loss(model, train_data, val_data, cfg)
            print(f"step {it}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

        xb, yb = get_batch(train_data, cfg.block_size, cfg.batch_size, cfg.device)
        logits, loss = model(xb, yb)
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()

    # --- generate a sample from the trained model ---
    context = torch.zeros((1, 1), dtype=torch.long, device=cfg.device)  # start token = id 0
    generated_ids = model.generate(context, max_new_tokens=500)[0].tolist()
    print("\n--- SAMPLE GENERATION ---")
    print(decode(generated_ids))

    torch.save(model.state_dict(), 'transformer_lm.pt')
    print("\nSaved weights to transformer_lm.pt")


if __name__ == '__main__':
    main()